### ISSUE TITLE
SF Jan 24 & 25 Rails Workshop at Pivotal Labs (@lilliealbert)

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/organizing#1]
Organizer: @lilliealbert
Venue: Pivotal Labs
Date: Jan 24/25
Curriculum: Rails

**TODOS**
- [x] Set Venue
- [x] Create Event on Bridge Troll
- [x] Order Installfest Pizza
- [x] Order Saturday breakfast
- [x] Order Lunch Catering
- [ ] Find place for afterparty
